version : '3'
services:
  app:
    container_name: 'app'
    build: .
    restart: always
    ports:
      - '3000:3000'
    working_dir: /user/src/app
    volumes:
      - .:/user/src/app
    environment:
      PORT: 3000
      DB_URI: "root:root@tcp(mysql:3306)/saas?parseTime=true"
    depends_on:
      - mysql
  mysql:
    container_name: 'mysql'
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ~/apps/mysql:/var/lib/mysql 
    environment:
      - MYSQL_DATABASE=saas
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root